use iced::keyboard;

use crate::gui::theme::Family;
use crate::state_machine::{self, EditorTool};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Menu {
    New,
    NewFromTabs,
    Operations,
    File,
    Export,
}

#[derive(Debug, Clone)]
pub enum Message {
    Canvas(state_machine::CanvasMessage),
    SelectTool(EditorTool),
    KeyPressed {
        key: keyboard::Key,
        modifiers: keyboard::Modifiers,
        captured: bool,
    },
    KeyReleased(keyboard::Key),
    Clear,
    EditTextChanged(String),
    FinishEditing,
    CancelEditing,
    ToggleMenu(Menu),
    CloseMenus,
    DismissModal,
    Noop,
    ChooseStartupModule(usize),
    StartupOpenFile,
    ExitApp,
    WindowCloseRequested,
    ConfirmCloseDiscard,
    ConfirmCloseSave,
    CancelClose,
    ToggleTheme,
    WindowResized(iced::Size),
    ToggleDock,
    ToggleShortcuts,
    ToastTick,
    DismissToast(u64),
    ZoomIn,
    ZoomOut,
    ZoomReset,
    FitView,
    OpenLoadDialog,
    LoadPathChanged(String),
    LoadBrowseClicked,
    LoadBrowseResult {
        picked: Option<Result<(String, String), String>>,
    },
    LoadPathSubmitted,
    CancelLoadDialog,
    OpenSaveDialog,
    SavePathChanged(String),
    SaveBrowseClicked,
    SaveBrowseResult { result: Result<String, String> },
    SavePathSubmitted,
    CancelSaveDialog,
    CopyLlmPrompt,
    CheckInput,
    DfaToNfa,
    Minimize,
    CheckInputTextChanged(String),
    SubmitCheckInput,
    CancelCheckInput,
    OpenRegexDialog,
    RegexTextChanged(String),
    SubmitRegex,
    CancelRegex,
    NewTab(Family),
    RemoveTab(usize),
    SwitchTab(usize),
    TabRenameChanged(String),
    TabRenameSubmit,
    RunInputChanged(String),
    RunLoad,
    RunStep,
    RunReset,
    RunTogglePlay,
    RunTick,
    GrammarEditorAction(iced::widget::text_editor::Action),
    GrammarWordChanged(String),
    GrammarParse,
    GrammarCheckWord,
    GrammarDerive,
    GrammarToCnf,
    CloseError,
    OpenLatexExport,
    CloseLatexExport,
    CopyLatexExport,
    OpenRegexExport,
    CloseRegexExport,
    CopyRegexExport,
    #[allow(dead_code)]
    OpenEditTransition((usize, usize)),
    EditTransitionLabelChanged(usize, String),
    SaveEditTransitionLabels,
    DeleteEditTransitionLabel(usize),
    AddEditTransitionLabel,
    CancelEditTransitionLabels,
}
