use iced::keyboard;

use crate::state_machine::{self, EditorTool};

#[derive(Debug, Clone)]
pub enum Message {
    Canvas(state_machine::CanvasMessage),
    SelectTool(EditorTool),
    KeyPressed(keyboard::Key),
    KeyReleased(keyboard::Key),
    Clear,
    EditTextChanged(String),
    FinishEditing,
    CancelEditing,
    ToggleOperationsMenu,
    ToggleMachineMenu,
    CloseMenus,
    DismissModal,
    Noop,
    ChooseStartupModule(usize),
    ExitApp,
    OpenLoadDialog,
    LoadPathChanged(String),
    LoadBrowseClicked,
    LoadBrowseResult {
        result: Result<(String, String), String>,
    },
    LoadPathSubmitted,
    CancelLoadDialog,
    ToggleFileMenu,
    OpenSaveDialog,
    SavePathChanged(String),
    SaveBrowseClicked,
    SaveBrowseResult { result: Result<(), String> },
    SavePathSubmitted,
    CancelSaveDialog,
    CopyLlmPrompt,
    CheckInput,
    DfaToNfa,
    Minimize,
    CheckInputTextChanged(String),
    SubmitCheckInput,
    CancelCheckInput,
    CloseCheckResultPopup,
    OpenRegexDialog,
    RegexTextChanged(String),
    SubmitRegex,
    CancelRegex,
    AddTab,
    RemoveTab(usize),
    SwitchTab(usize),
    AddTuringTab,
    TmInputChanged(String),
    TmLoadInput,
    TmStep,
    TmReset,
    TmTogglePlay,
    AddPushdownTab,
    PdaInputChanged(String),
    PdaLoadInput,
    PdaStep,
    PdaReset,
    PdaTogglePlay,
    FiniteInputChanged(String),
    FiniteLoadInput,
    FiniteStep,
    FiniteReset,
    FiniteTogglePlay,
    RunTick,
    AddGrammarTab,
    GrammarEditorAction(iced::widget::text_editor::Action),
    GrammarWordChanged(String),
    GrammarParse,
    GrammarCheckWord,
    GrammarDerive,
    GrammarToCnf,
    CloseError,
    OpenLatexExport,
    CloseLatexExport,
    CopyLatexExport,
    OpenRegexExport,
    CloseRegexExport,
    CopyRegexExport,
    #[allow(dead_code)]
    OpenEditTransition((usize, usize)),
    EditTransitionLabelChanged(usize, String),
    SaveEditTransitionLabels,
    DeleteEditTransitionLabel(usize),
    AddEditTransitionLabel,
    CancelEditTransitionLabels,
}
