use iced::keyboard;

use crate::gui::theme::Family;
use crate::state_machine::{self, EditorTool};

/* Header dropdown menus; at most one is open at a time. */
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Menu {
    /* New-entity menu, anchored under its header trigger. */
    New,
    /* The same entity list, anchored at the tab bar's "+" button. */
    NewFromTabs,
    Operations,
    File,
    Export,
}

#[derive(Debug, Clone)]
pub enum Message {
    Canvas(state_machine::CanvasMessage),
    SelectTool(EditorTool),
    /* `captured` is true when a focused widget (text input) already
     * consumed the key, so single-key shortcuts must stay inert. */
    KeyPressed {
        key: keyboard::Key,
        modifiers: keyboard::Modifiers,
        captured: bool,
    },
    KeyReleased(keyboard::Key),
    Clear,
    EditTextChanged(String),
    FinishEditing,
    CancelEditing,
    ToggleMenu(Menu),
    CloseMenus,
    DismissModal,
    Noop,
    ChooseStartupModule(usize),
    StartupOpenFile,
    ExitApp,
    /* The window's close button (the app intercepts it to protect unsaved
     * work). */
    WindowCloseRequested,
    // Unsaved-changes confirmation.
    ConfirmCloseDiscard,
    ConfirmCloseSave,
    CancelClose,
    ToggleTheme,
    WindowResized(iced::Size),
    ToggleDock,
    ToggleShortcuts,
    ToastTick,
    DismissToast(u64),
    ZoomIn,
    ZoomOut,
    ZoomReset,
    FitView,
    OpenLoadDialog,
    LoadPathChanged(String),
    LoadBrowseClicked,
    LoadBrowseResult {
        result: Result<(String, String), String>,
    },
    LoadPathSubmitted,
    CancelLoadDialog,
    OpenSaveDialog,
    SavePathChanged(String),
    SaveBrowseClicked,
    SaveBrowseResult { result: Result<String, String> },
    SavePathSubmitted,
    CancelSaveDialog,
    CopyLlmPrompt,
    CheckInput,
    DfaToNfa,
    Minimize,
    CheckInputTextChanged(String),
    SubmitCheckInput,
    CancelCheckInput,
    OpenRegexDialog,
    RegexTextChanged(String),
    SubmitRegex,
    CancelRegex,
    NewTab(Family),
    RemoveTab(usize),
    SwitchTab(usize),
    TabRenameChanged(String),
    TabRenameSubmit,
    TmInputChanged(String),
    TmLoadInput,
    TmStep,
    TmReset,
    TmTogglePlay,
    PdaInputChanged(String),
    PdaLoadInput,
    PdaStep,
    PdaReset,
    PdaTogglePlay,
    FiniteInputChanged(String),
    FiniteLoadInput,
    FiniteStep,
    FiniteReset,
    FiniteTogglePlay,
    RunTick,
    GrammarEditorAction(iced::widget::text_editor::Action),
    GrammarWordChanged(String),
    GrammarParse,
    GrammarCheckWord,
    GrammarDerive,
    GrammarToCnf,
    CloseError,
    OpenLatexExport,
    CloseLatexExport,
    CopyLatexExport,
    OpenRegexExport,
    CloseRegexExport,
    CopyRegexExport,
    #[allow(dead_code)]
    OpenEditTransition((usize, usize)),
    EditTransitionLabelChanged(usize, String),
    SaveEditTransitionLabels,
    DeleteEditTransitionLabel(usize),
    AddEditTransitionLabel,
    CancelEditTransitionLabels,
}
